services:
  php:
    container_name: php_adm_php
    restart: unless-stopped
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - adm_network

networks:
  adm_network: